# Generated by Django 2.1.1 on 2018-11-22 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181122_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='main.Language')),
            ],
            options={
                'db_table': 'technologies',
            },
        ),
        migrations.RemoveField(
            model_name='framework',
            name='language',
        ),
        migrations.RenameField(
            model_name='errormessage',
            old_name='framework',
            new_name='language',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='associated_frameworks',
        ),
        migrations.DeleteModel(
            name='Framework',
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='associated_technologies',
            field=models.ManyToManyField(related_name='student_errors', to='main.Technology'),
        ),
    ]
