# Generated by Django 2.1.1 on 2018-11-22 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181122_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmission',
            name='associated_technologies',
            field=models.ManyToManyField(related_name='student_submissions', to='main.Technology'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='technology',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technologies', to='main.Language'),
        ),
    ]
